name: Snapshot

on: workflow_dispatch

jobs:
  snapshot:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      CI: true
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/composite-actions/setup-pnpm
      - name: Publish snapshot
        uses: seek-oss/changesets-snapshot@v0
        with:
          pre-publish: pnpm prepare-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
